#!/bin/bash
#
# sudo apt-get install -y festival
#
# http://festvox.org/docs/manual-1.4.3/festival_29.html
#

cat <<EOF > doremi.xml
<?xml version="1.0"?>
<!DOCTYPE SINGING PUBLIC "-//SINGING//DTD SINGING mark up//EN"
      "Singing.v0_1.dtd"
[]>
<SINGING BPM="30">
<PITCH NOTE="G3"><DURATION BEATS="0.3">doe</DURATION></PITCH>
<PITCH NOTE="A3"><DURATION BEATS="0.3">ray</DURATION></PITCH>
<PITCH NOTE="B3"><DURATION BEATS="0.3">me</DURATION></PITCH>
<PITCH NOTE="C4"><DURATION BEATS="0.3">fah</DURATION></PITCH>
<PITCH NOTE="D4"><DURATION BEATS="0.3">sew</DURATION></PITCH>
<PITCH NOTE="E4"><DURATION BEATS="0.3">lah</DURATION></PITCH>
<PITCH NOTE="F#4"><DURATION BEATS="0.3">tee</DURATION></PITCH>
<PITCH NOTE="G4"><DURATION BEATS="0.3">doe</DURATION></PITCH>
</SINGING>
EOF

cat <<EOF > doremi1.xml
<?xml version="1.0"?>
<!DOCTYPE SINGING PUBLIC "-//SINGING//DTD SINGING mark up//EN"
      "Singing.v0_1.dtd"
[]>
<SINGING BPM="30">
<PITCH NOTE="G3"><DURATION BEATS="0.5">doe</DURATION></PITCH>
<PITCH NOTE="A3"><DURATION BEATS="0.15">ray</DURATION></PITCH>
<PITCH NOTE="B3"><DURATION BEATS="0.15">me</DURATION></PITCH>
<PITCH NOTE="C4"><DURATION BEATS="0.5">fah</DURATION></PITCH>
<PITCH NOTE="D4"><DURATION BEATS="0.125">sew</DURATION></PITCH>
<PITCH NOTE="E4"><DURATION BEATS="0.125">lah</DURATION></PITCH>
<PITCH NOTE="F#4"><DURATION BEATS="0.5">tee</DURATION></PITCH>
<PITCH NOTE="G4"><DURATION BEATS="0.5">doe</DURATION></PITCH>
</SINGING>
EOF

# festival> (tts "doremi.xml" 'singing)

text2wave -mode singing doremi.xml -o doremi.wav
text2wave -mode singing doremi1.xml -o doremi1.wav
