#!/bin/bash

txt="$1"
bpm=120

if [[ "$txt" == "" ]] ; then
  echo "provide text"
  exit 1
fi

text2wave -eval '(voice_us1_mbrola)' -mode singing <( ./singsay-xml -b ${bpm} "${txt}" ) -o XXX.wav
aplay XXX.wav
